### ISSUE TITLE
Rearrange data path structure to start with levels

### ISSUE THREAD

**Issue by ninarobbins** [Geet-George/halodrops#115]
keep backwards compatibility, to easily be able to process older folder structures, but keep the new one as the default.

Suggested new structure:

> Level 0
      | flight 1 ...
           | sonde 1 (.nc) ...
> Level 1
      | flight 1 ...
           | sonde 1 (.nc) ...
> Level 2
      | flight 1 ...
           | sonde 1 (.nc) ...
> Level 3
      one dataset (.nc)

**Comment by hgloeckner** [comment]
arbitrary with #135 -> data structure is now arbitrary
