### ISSUE TITLE
Inspecting functions

### ISSUE THREAD

**Issue by hdorff94** [Geet-George/halodrops#31]
Inspecting functions for their arguments. The outcoming information of arguments is then used to check if new entries for the function are specified in the config-file.

**Comment by Geet-George** [comment]
So, I put together some things, which are explained in more details in #35. I feel we have something we can work as a basic framework. Of course, things like reading from the MANDATORY section remains. @hdorff94 don't feel stressed to work on this issue if you have more pressing things to do, I understand you have a tight timeline.
