### ISSUE TITLE
Remove CONFIG file from package

### ISSUE THREAD

**Issue by Geet-George** [Geet-George/halodrops#32]
Should a default config file be part of the package? What are the advantages & pitfalls?

**Comment by ninarobbins** [comment]
Hi @Geet-George, I was just thinking about this. It is nice to have a sample config to know how to structure it, but I find it nice to have a user config file which can be modified freely without keeping track of the changes. In the lidar processing code we have a standard config which never changes, and a user config file in which we can add the fields we want to modify, but it is ignored by git. I don't know if this is overkill. Or we could just add the config file to "gitignore", but I'm not sure if that's the best way.

**Comment by Geet-George** [comment]
Hi @ninarobbins, thanks for the comments. I think a standard config could be provided, but that would involve the minimal:

```
[MANDATORY]
data_directory = 'path/to/your/data/root/dir'
```

I see that we already have a ["sample"](https://github.com/Geet-George/halodrops/blob/main/halodrops.cfg), although it is outdated and should change. A user config can be maintained by users as they wish and added to gitignore. Did I understand you correctly?

**Comment by Geet-George** [comment]
@ninarobbins I think the changes in #113 of providing a minimal config is enough. The documentation should be good enough for the user to know how to add fields to the config file, otherwise we would have to include all possible permutations in the config file, which is all arguments of mostly all functions in the package. Therefore, I'll close this for now. But please feel free to re-open if I misunderstood what you said. And thanks for bringing attention to this issue again :)

**Comment by ninarobbins** [comment]
@Geet-George  yes that's what I meant! Sorry if this is something you've already done. But I was wondering since the issue is open. I'm thinking if we should add the user config to gitignore already and encourage people to use a standard name ("user_config" or something)

**Comment by ninarobbins** [comment]
@Geet-George I was to slow!! :D this sounds like a good solution.
